apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: exercises/helm-nginx 
    repoURL: https://github.com/Query-Interface/nd064_course_1 
    targetRevision: HEAD
